// flow-typed signature: 029aa6f9e94aed0a91a80f23a4d1c0f5
// flow-typed version: <<STUB>>/eslint-config-mcansh_v1.1.1/flow_v0.99.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-mcansh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-mcansh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-mcansh/base' {
  declare module.exports: any;
}

declare module 'eslint-config-mcansh/typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-mcansh/base.js' {
  declare module.exports: $Exports<'eslint-config-mcansh/base'>;
}
declare module 'eslint-config-mcansh/index' {
  declare module.exports: $Exports<'eslint-config-mcansh'>;
}
declare module 'eslint-config-mcansh/index.js' {
  declare module.exports: $Exports<'eslint-config-mcansh'>;
}
declare module 'eslint-config-mcansh/typescript.js' {
  declare module.exports: $Exports<'eslint-config-mcansh/typescript'>;
}
