// flow-typed signature: 5dad6494164021c9dfeed03d35d76b67
// flow-typed version: <<STUB>>/@mcansh/eslint-config_v2.3.1-canary.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mcansh/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mcansh/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mcansh/eslint-config/base' {
  declare module.exports: any;
}

declare module '@mcansh/eslint-config/prettier.config' {
  declare module.exports: any;
}

declare module '@mcansh/eslint-config/stylelint.config' {
  declare module.exports: any;
}

declare module '@mcansh/eslint-config/ts-no-babel' {
  declare module.exports: any;
}

declare module '@mcansh/eslint-config/ts-strict' {
  declare module.exports: any;
}

declare module '@mcansh/eslint-config/typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mcansh/eslint-config/base.js' {
  declare module.exports: $Exports<'@mcansh/eslint-config/base'>;
}
declare module '@mcansh/eslint-config/index' {
  declare module.exports: $Exports<'@mcansh/eslint-config'>;
}
declare module '@mcansh/eslint-config/index.js' {
  declare module.exports: $Exports<'@mcansh/eslint-config'>;
}
declare module '@mcansh/eslint-config/prettier.config.js' {
  declare module.exports: $Exports<'@mcansh/eslint-config/prettier.config'>;
}
declare module '@mcansh/eslint-config/stylelint.config.js' {
  declare module.exports: $Exports<'@mcansh/eslint-config/stylelint.config'>;
}
declare module '@mcansh/eslint-config/ts-no-babel.js' {
  declare module.exports: $Exports<'@mcansh/eslint-config/ts-no-babel'>;
}
declare module '@mcansh/eslint-config/ts-strict.js' {
  declare module.exports: $Exports<'@mcansh/eslint-config/ts-strict'>;
}
declare module '@mcansh/eslint-config/typescript.js' {
  declare module.exports: $Exports<'@mcansh/eslint-config/typescript'>;
}
